### ISSUE TITLE
Revisar el código del script inicial

### ISSUE THREAD

**Issue by FedeGaleano** [LPapazian/jugo-de-naranja-GDD#1]
Output:

Msg 1767, Level 16, State 0, Line 3
Foreign key 'FK_cliente_usuario' references invalid table 'JUGO_DE_NARANJA.Usuarios'.
Msg 1750, Level 16, State 0, Line 3
Could not create constraint. See previous errors.
Msg 1778, Level 16, State 0, Line 1
Column 'JUGO_DE_NARANJA.Pagos.pago_id' is not the same data type as referencing column 'Viaje.viaje_pago' in foreign key 'FK_viaje_pago'.
Msg 1750, Level 16, State 0, Line 1
Could not create constraint. See previous errors.
Msg 1767, Level 16, State 0, Line 2
Foreign key 'FK_chofer_usuario' references invalid table 'JUGO_DE_NARANJA.Usuarios'.
Msg 1750, Level 16, State 0, Line 2
Could not create constraint. See previous errors.
Msg 1767, Level 16, State 0, Line 2
Foreign key 'FK_usuario_rol_usuario' references invalid table 'JUGO_DE_NARANJA.Usuarios'.
Msg 1750, Level 16, State 0, Line 2
Could not create constraint. See previous errors.

IMPORTANTE: Probar el código antes de pushear

**Comment by ankomas** [comment]
Ya lo arregle

**Comment by FedeGaleano** [comment]
Buenísimo!
